REPOS={
    "attendance-system":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/attendance-system.git",
        "type":"project"
        },
    "detection-pipeline":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/detection-pipeline.git",
        "type":"project"
        },
    "fast-image-classification":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/Fast-Image-Classification.git",
        "type":"project"
        },
    "drone-redtail":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/redtail.git",
        "type":"project"
        },
    "uav-imagery":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/UAV_For_Disaster_Management.git",
        "type":"project"
        },
    "cnn-slam":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/CNN_SLAM.git",
        "type":"project"
        },
    "holojest":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/holojest.git",
        "type":"project"
        },
    "super-resolution":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/Super-Resolution.git",
        "type":"project"
        },
    "pix2pix-mountains":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/webcam-pix2pix-tensorflow.git",
        "type":"project"
        },
    "cell-segmentation":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/Cell-Segmentation.git",
        "type":"project"
        },
    "activity-recognition-deep-pose":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/Activity-Recognition-Deep-Pose.git",
        "type":"project"
        },
     "dockerfiles":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/workstation.git",
        "type":"utils"
        },
    "ubuntu-setup":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/Ubuntu-Setup-Scripts.git",
        "type":"utils"
        },
    "raspberry-setup":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/Raspberry_Setup.git",
        "type":"utils"
        }
}