REPOS={
    "attendance-system":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/attendance-system.git",
        "type":"project"
        },
    "detection-pipeline":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/detection-pipeline.git",
        "type":"project"
        },
    "drone-redtail":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/redtail.git",
        "type":"project"
        },
    "cnn-slam":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/CNN_SLAM.git",
        "type":"project"
        },
     "dockerfiles":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/workstation.git",
        "type":"tools"
        },
    "ubuntu-setup":{
        "refresh":True,
        "link":"https://github.com/iitmcvg/Ubuntu-Setup-Scripts.git",
        "type":"tools"
        },
    "holojest":{
    "refresh":True,
    "link":"https://github.com/iitmcvg/holojest.git",
    "type":"project"
    }
}